### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by jfsantos** [datalogai/recurrentshop#1]
First of all, thanks for working on such a useful library!

I noticed you chose GPL-3 as a license, which is much more restrictive than Keras' license (MIT). Is there any chance you could relicense to a less restrictive license, such as MIT or BSD?

Thanks!

**Comment by farizrahman4u** [comment]
@malaikannan

**Comment by malaikannan** [comment]
@jfsantos modified license from GPL to MIT.

**Comment by jfsantos** [comment]
Thanks!
