### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by firearasi** [datalogai/recurrentshop#17]
For python3,
line 516 of [https://github.com/datalogai/recurrentshop/blob/master/recurrentshop/engine.py](url)
`x = map(x.get, args)`
should be:
`x = list(map(x.get, args))`
Otherwise, one would get the following error:

> 

  File "/usr/lib/python3.5/site-packages/recurrentshop-0.0.1-py3.5.egg/recurrentshop/engine.py", line 522, in __call__
    if x[i] is not None:

TypeError: 'map' object is not subscriptable

**Comment by farizrahman4u** [comment]
fixed
