### ISSUE TITLE
Initializing the hidden state of a RNN with the output of a previous layer

### ISSUE THREAD

**Issue by dr-costas** [datalogai/recurrentshop#18]
Hi, 

Can someone provide a minimal example for initializing the hidden state of a RNN with the output of a previous layer and with RecurrentShop?

**Comment by farizrahman4u** [comment]
```python
rc = RecurrentContainer()
rc.add(...)
y = rc({'input': x, 'states': [state]})
```

**Comment by dr-costas** [comment]
Hi, 

If someone uses the dict call of the recurrentcontainer and also uses initial readout (or states) then the inputs at engine.py, line 332 the mask in a list. 

This causes an exception at the rnn function of the backend file.

**Comment by farizrahman4u** [comment]
@dr-costas Would you be interested in creating a pull request that fixes the issue?

**Comment by dr-costas** [comment]
@farizrahman4u , sure! If the issue can wait a bit, I surely can try and find a solution.

**Comment by cagdasbas** [comment]
Hi,

Can you give a more detailed example about this? A two layer rnn with input? I've had trouble compiling the model with the input layer dimension.

Thanks.
