### ISSUE TITLE
AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_LEARNING_PHASE'

### ISSUE THREAD

**Issue by bill3code** [datalogai/recurrentshop#20]
Hello!

I try to use tensorflow as backend, and got this error.

> AttributeError                            Traceback (most recent call last)
> <ipython-input-12-e70bf8f0da04> in <module>()
>       1 model = Sequential()
> ----> 2 model.add(Seq2Seq(input_shape=(inpLen, inpDim), output_length=inpLen, output_dim=inpDim, hidden_dim = 100, dropout=0.3,depth=2))
>       3 model.add(Activation('softmax'))
>       4 model.compile(loss='categorical_crossentropy', optimizer='adam')
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\seq2seq-0.1.0-py3.5.egg\seq2seq\models.py in Seq2Seq(output_dim, output_length, hidden_dim, depth, broadcast_state, inner_broadcast_state, teacher_force, peek, dropout, **kwargs)
>     180         input._keras_history[0].supports_masking = True
>     181         encoded_seq = dense1(input)
> --> 182         encoded_seq = encoder(encoded_seq)
>     183         if broadcast_state:
>     184                 states = encoded_seq[-2:]
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\recurrentshop-0.0.1-py3.5.egg\recurrentshop\engine.py in __call__(self, x, mask)
>     569                                 break
>     570                 if inbound_layers:
> --> 571                         self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
>     572                         input_added = True
>     573                 if input_added:
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\keras\engine\topology.py in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
>     569         # creating the node automatically updates self.inbound_nodes
>     570         # as well as outbound_nodes on inbound layers.
> --> 571         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
>     572 
>     573     def get_output_shape_for(self, input_shape):
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\keras\engine\topology.py in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
>     153 
>     154         if len(input_tensors) == 1:
> --> 155             output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
>     156             output_masks = to_list(outbound_layer.compute_mask(input_tensors[0], input_masks[0]))
>     157             # TODO: try to auto-infer shape if exception is raised by get_output_shape_for.
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\recurrentshop-0.0.1-py3.5.egg\recurrentshop\engine.py in call(self, x, mask)
>     329                 else:
>     330                         if self.uses_learning_phase:
> --> 331                                 with learning_phase(0):
>     332                                         last_output_0, outputs_0, states_0, updates = rnn(self.step, x, initial_states, go_backwards=self.go_backwards, mask=mask, unroll=unroll, input_length=input_shape[1])
>     333                                 with learning_phase(1):
> 
> C:\Users\Public\Documents\Python2\lib\site-packages\recurrentshop-0.0.1-py3.5.egg\recurrentshop\engine.py in __enter__(self)
>      39 
>      40         def __enter__(self):
> ---> 41                 self.learning_phase_place_holder = _backend._LEARNING_PHASE
>      42                 _backend._LEARNING_PHASE = self.value
>      43 
> 
> AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_LEARNING_PHASE'

**Comment by bill3code** [comment]
I got this error then use something like:

```
model = Sequential()
model.add(SimpleSeq2Seq(input_shape=(inpLen, inpDim), output_length=inpLen, output_dim=inpDim, hidden_dim = hiddenDim, dropout=dropOut ,depth=2))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
```

**Comment by valtsblukis** [comment]
Same here. The problem arises when using Dropout or possibly any other layer that has different training and testing time behavior. I tried to fix it myself, but ended up getting even deeper in trouble.

**Comment by israelg99** [comment]
Any ideas @farizrahman4u ?

**Comment by farizrahman4u** [comment]
All fixed. See docs.
