### ISSUE TITLE
More documentation and Example

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [datalogai/recurrentshop#22]
Hi @farizrahman4u 
Your packages (both seq2seq and recurrentshop) are unbelievably useful, but they both require more documentation and example as well as reference part for all available predefined layers.

Could you please provide us with such necessary examples, documentations, and glossaries?

I can help you if don't have enough time...just ping me in that case...

**Comment by farizrahman4u** [comment]
Added docs/
