### ISSUE TITLE
Does recurrentshop support Bidirection RNN?

### ISSUE THREAD

**Issue by ganji15** [datalogai/recurrentshop#24]
@farizrahman4u

Does recurrentshop support a bidirectional RNN or a backward-directional RNN?  
Dose it behaves like RNN in original keras package?
Is there any examples avaliable?

Thank you very much!

**Comment by farizrahman4u** [comment]
Yes.. you can use the Bidirectional wrapper from Keras..

**Comment by ganji15** [comment]
@farizrahman4u 
Thank you very much! Very useful package!
