### ISSUE TITLE
Check current usage of a simple model with readout=call and use readout as Input to another layer

### ISSUE THREAD

**Issue by pbaljeka** [datalogai/recurrentshop#29]
I have the following RecurrentContainer:- 3 layer LSTM + linear RNN layer.
``
rc = RecurrentContainer(readout='call', return_sequences=True, stateful=False, input_shape=    (timesteps,  n_input_dim))
``
``
rc.add(LSTMCell(hidden_size, input_dim=n_input_dim, activation='tanh'))
``
``
rc.add(LSTMCell(hidden_size, activation='tanh'))
``
``
rc.add(LSTMCell(hidden_size, activation='tanh'))
``
``
rc.add(SimpleRNNCell(n_output_dim, activation='linear'))
``
``
input_seq = Input(shape=(timesteps, n_input_dim,))
``
``
output_seq=rc(input_seq)
``
1. Is this the correct usage in the case where I want the input to be something like input_seq(t), output_seq(t-1) . Since  readout=call gives me the same result as readout=False. 
2. How do I access the readout, so that I can use it as an input to another layer?

**Comment by farizrahman4u** [comment]
Feature is documented in docs/readout (recurrentshop-1 branch)
