### ISSUE TITLE
keras integration errors

### ISSUE THREAD

**Issue by sunnysai12345** [datalogai/recurrentshop#32]
from keras import initializations, regularizers, constraints
from keras.utils.layer_utils import layer_from_config
sol:No initializations ??Modified to Initializers.
what about layer_from_config

**Comment by sunnysai12345** [comment]
Modified code to make it work with latest version of keras #33 .

**Comment by xuyiqiang-learn** [comment]
how about layer_from_config? Did you solve the problem?

**Comment by sunnysai12345** [comment]
Yes

**Comment by xuyiqiang-learn** [comment]
Can you tell me how to solve this problem?　thank you!

**Comment by sunnysai12345** [comment]
The layer_from_config is deprecated in keras latest versions which is replaced with deserialize I opened a pull request u can find the modified changes here #33

**Comment by xuyiqiang-learn** [comment]
really thank you !

**Comment by farizrahman4u** [comment]
See recurrentshop-1 branch.
