### ISSUE TITLE
Installation error: ImportError: cannot import name initializations

### ISSUE THREAD

**Issue by vin101** [datalogai/recurrentshop#35]
I am getting the following error when I am trying to install recurrentshop:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "recurrentshop/__init__.py", line 1, in <module>
    from .engine import RNNCell, RecurrentContainer, weight
  File "recurrentshop/engine.py", line 3, in <module>
    from keras import initializations, regularizers, constraints
ImportError: cannot import name initializations`

I have keras and tensorflow running, using ubuntu. Any help would be appreciated

**Comment by soeraa** [comment]
Look here: https://github.com/datalogai/recurrentshop/pull/33

**Comment by wangyufish** [comment]
This error is still exist, how should I solve it? Thanks!

**Comment by zhubinjun** [comment]
Yes, the error is still exist. But it only exist when I use the keras2.
After I downgrade the keras to 1.2.0, the package works.

**Comment by smaknet** [comment]
Keras has replaced keras.initializations to keras.initializers

**Comment by lkluo** [comment]
keras 2 has been released, recurrentshop shall upgrade as well

**Comment by farizrahman4u** [comment]
Guys, please switch to recurrentshop-1 branch.
