### ISSUE TITLE
AttributeError: 'LSTMCell' object has no attribute 'uses_learning_phase'

### ISSUE THREAD

**Issue by wangyufish** [datalogai/recurrentshop#36]
Hi, I guess this error also caused by keras version 2, but I do not know how to fix it. Is anybody here can help me?

**Comment by 0xnurl** [comment]
Line #203 in `engine.py` should be changed to:
```
self.uses_learning_phase = self._truth_tensor or any([l.uses_learning_phase for l in self.model.layers if hasattr(l, 'uses_learning_phase')])
```

(this fixed the problem with `uses_learning_phase` but obviously led to a lot more errors)

**Comment by farizrahman4u** [comment]
Please switch to recurrentshop-1 branch.
