### ISSUE TITLE
engine.py: indentation error in line 42 and import * only allowed at module level in line 41 

### ISSUE THREAD

**Issue by skeydan** [datalogai/recurrentshop#52]
Hi,

I've just updated recurrentshop to work with keras 2 (to  keras-2.0.3 recurrentshop-1.0.0) and now on

`import recurrentshop` I get an indentation error at line 42 of engine.py.

When I correct the indentation the next error is

` File "/home/key/software/anaconda3/envs/tf3.5/lib/python3.5/site-packages/recurrentshop/engine.py", line 41
    def _get_cells():
                     ^
SyntaxError: import * only allowed at module level`

Could you please have a look?
Thx!

**Comment by farizrahman4u** [comment]
@abhaikollara Can you test on python3?

**Comment by abhaikollara** [comment]
Yup, getting the same error here

**Comment by farizrahman4u** [comment]
What about now?

**Comment by abhaikollara** [comment]
Works fine now

**Comment by farizrahman4u** [comment]
Cool, thanks.
