### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by MSchuwalow** [datalogai/recurrentshop#68]
There are some tabs instead of spaces at https://github.com/datalogai/recurrentshop/blob/master/recurrentshop/engine.py#L459-L462.
This causes the error from the title at import.

**Comment by abhaikollara** [comment]
@MSchuwalow Update RecurrentShop, PEP8 fixes have been done throughout. Thanks

**Comment by MSchuwalow** [comment]
Yep problem is fixed. closing
