### ISSUE TITLE
Undefined functions

### ISSUE THREAD

**Issue by inzaghi250** [datalogai/recurrentshop#73]
https://github.com/datalogai/recurrentshop/blob/bb9a600374b0b481aeea9f9230c197b9329a2033/recurrentshop/backend/theano_backend.py#L75

https://github.com/datalogai/recurrentshop/blob/bb9a600374b0b481aeea9f9230c197b9329a2033/recurrentshop/backend/theano_backend.py#L91

Should the above two functions be from numpy, e.g., np.expand_dims?

**Comment by farizrahman4u** [comment]
Fixed. Thanks.
