### ISSUE TITLE
What's the difference between readout and decode, conceptually?

### ISSUE THREAD

**Issue by phdowling** [datalogai/recurrentshop#8]
First of all, this library looks like a great addition to Keras, thanks for providing it. Now for my question: This might be obvious, but I'm not totally clear on the uses of `readout=True` and `decode=True` in your examples. When would I use either one, and when would I want to specify both arguments?

I see that `decode=True` requires setting an output length (so it can be used for n-to-m seq2seq learning), and that `readout` simply basically adds the previous timesteps final output to the current input. Isn't this sort of  "readout" required for decoders in most settings? When does `readout=True` by itself become useful? Also, slightly less related: how do I use the RecurrentContainer to specify the initial hidden state of a decoder?

Finally, there seem to be multiple readout modes: https://github.com/datalogai/recurrentshop/blob/master/recurrentshop/engine.py#L244-L251 , are they documented somewhere?

I know these are a lot of questions, but perhaps you could just generally clarify the concepts a little. Thank you.

**Comment by farizrahman4u** [comment]
Readout is useful when you have a stack of rnn cells, and you want the output of the top cell at time t be available to the bottom cell at t-1. 
For initializing the hidden states of a recurrent container, simple create one (`rc = RecurrentContainer(...)`), build it (`rc.build(input_shape)`) and reset the states (`rc.states=[list of tensors]`).

**Comment by phdowling** [comment]
I see, thanks. Doesn't a decoder always need the `readout=True` flag then?

**Comment by farizrahman4u** [comment]
Not really.. since readout is not the only information being transferred across time. There are states too.

**Comment by phdowling** [comment]
Ah, yes that makes sense. Just out of curiosity: do you transfer the raw class probabilities tensor as input to the next timestep, or the one-hot encoded argmax, i.e. the resulting classification?
